### ISSUE TITLE
Tests such as Test/Unitest/pal_all_test_main... should be platform independent

### ISSUE THREAD

**Issue by rgrover** [ARMmbed/pal#12]
https://github.com/ARMmbed/pal/blob/master/Test/Unitest/pal_all_test_main_mbedOS.cpp#L17

Perhaps we don't need `mbed.h`? Can't the tests be platform-neutral?

**Comment by rgrover** [comment]
Could we please also remove uses of `fflush()` and `putchar()`. Certain platforms may not support these.

**Comment by mohammad1603** [comment]
Thanks for the comment, for different platforms we do need different code for platform initializations, different includes , etc. So the main function file can not be neutral. the needed pal_$(MODULE)_main_$(PLATFORM).cpp file will be taken in compile time according to the target platform.

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.

Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.

Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
