### ISSUE TITLE
drop 'All rights reserved.' from apache-2.0 license headers

### ISSUE THREAD

**Issue by rgrover** [ARMmbed/pal#13]
``` C++
* Copyright (c) 2016 ARM Limited. All rights reserved.
```

should be turned into 

``` C++
* Copyright (c) 2016 ARM Limited.
```

This is found in nearly all license headers.

**Comment by NirSonnenschein** [comment]
Hi Rohit, 
thanks for all of your inputs we really apprciate them. we will work to correct the issues you brought up.
could you tell me what is the context of the review (all reviews of the code are good as they help us prevent issues, but knowing the context can help use prioritize the fixes).
 regarding the copyright headers, there were the last ones we were instructed to place in the code. I haven't been iformaed of a need to change them before this. I'll check if we need to modify as you noted above. 

Thanks, 
   Nir S.

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.

Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.

Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
