### ISSUE TITLE
PAL_SUCCESS should be defined within pal_errors.h

### ISSUE THREAD

**Issue by rgrover** [ARMmbed/pal#16]
PAL_SUCCESS should be defined alongside (or in the vicinity of) other error codes (in `pal_errors.h`).
A user looking for error codes is more likely to know about PAL_SUCCESS, and then (s)he should be able to discover other error codes based on a search for PAL_SUCCESS.

I suggest defining PAL_SUCCESS _within_ the `palError_t` enumeration; that way there would be a compiler enforced guarantee that no error enumerator will overlap its value with PAL_SUCCESS.

**Comment by NirSonnenschein** [comment]
Thanks for your suggestions, I agree they make a lot of sense (although strictly speaking the PAL_SUCCESS value is not an actual error). We will consider changing this.

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.

Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.

Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
