### ISSUE TITLE
Not clear if pal_plat_osTimerStart() should accept the value 0 for the `millisec` parameter

### ISSUE THREAD

**Issue by rgrover** [ARMmbed/pal#21]
What should the system do if a timer is started with a timeout value of 0? Is this a param error? or should the function callback be invoked immediately?

**Comment by rgrover** [comment]
In more general terms, depending upon the definition of a `tick`, the documentation should clarify the platform's behavior when the `millisec` parameter specifies a timeout which is smaller than (or equal to) a single tick.

**Comment by mohammad1603** [comment]
Thanks for the comment,  we added more info to the documentation for the cases:
1- single system tick interval.
2- in timeout value 0 case, the function returns "PAL_ERR_RTOS_VALUE" error. 
documentation fix will be available in the upcoming PAL release.

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.

Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.

Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
