### ISSUE TITLE
pal_osPoolCreate() may be inappropriate for platforms with only static memory allocators

### ISSUE THREAD

**Issue by rgrover** [ARMmbed/pal#27]
`pal_osPoolCreate()` is a runtime allocator---its implementation requires use of a dynamic memory allocator as a backend. Some platforms may only want to work with static (compile-time) allocators. 

This is similar in spirit to issue https://github.com/ARMmbed/pal/issues/23.

**Comment by rgrover** [comment]
Allowing for static allocation would result in much better use of memory in most cases. Otherwise, dynamic allocation would need to cater to a wider parameter range and therefore over-allocate resources. When working with dynamic allocation, the platform-implementor needs to pick an arbitrary limit on the size of the backend memory pool reserved for  `pal_osPoolCreate()`, or else rely upon a generic memory allocator. This is clearly suboptimal.

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.

Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.

Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
