### ISSUE TITLE
documentation for pal_osMessageQueueCreate() has copy-paste errors

### ISSUE THREAD

**Issue by rgrover** [ARMmbed/pal#28]
```
/*! Create and initialize a message queue.
*
* @param[in] messageQSize: size of the message queue.
* @param[out] memoryPoolID: holds the created memory pool ID handle - zero value indecates an error.
*
* \return PAL_SUCCESS when message queue created successfully.
*         Specific error in case of failure.
*/
palStatus_t pal_osMessageQueueCreate(uint32_t messageQSize, palMessageQID_t* messageQID);
```

Notice that the documentation (above) describes the second parameter as `memoryPoolID` (instead of `messageQID`).

**Comment by mohammad1603** [comment]
Thanks for your comment, it will be fixed in the upcoming release.

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.

Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.

Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
