### ISSUE TITLE
spelling mistakes in pal_rtos.h

### ISSUE THREAD

**Issue by rgrover** [ARMmbed/pal#29]
`millieseconds`
`priotity`
`sotre`
`indecates`
`avaialbe`

**Comment by NirSonnenschein** [comment]
Thanks,
We will fix this as soon as we can.

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.

Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.

Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
