### ISSUE TITLE
possible confusion in pal_osMessageQueue APIs around what goes into a queue

### ISSUE THREAD

**Issue by rgrover** [ARMmbed/pal#30]
consider `pal_osMessageQueueCreate`

``` C++
/*! Create and initialize a message queue.
*
* @param[in] messageQSize: size of the message queue.
* @param[out] memoryPoolID: holds the created memory pool ID handle - zero value indicates an error.
*
* \return PAL_SUCCESS when message queue created successfully.
*         Specific error in case of failure.
*/
palStatus_t pal_osMessageQueueCreate(uint32_t messageQSize, palMessageQID_t* messageQID);
```

I feel that there is lack of clarity in the documentation around what goes into the queue. Is `messageQSize` the 'count' of the number items which can be put into the queue or is it the size (?in bytes?) of the queue assuming that items going into the queue are `uint32_t` values?

It seems from `pal_osMessagePut()` that a `uint32_t info` is expected. Perhaps this should be `uintptr_t`.

If `messageQSize` is a count of items, then perhaps `size_t` is a better type for it.

Won't it be more useful if message queues can be created for arbitrary sized data items (instead of limiting item-values to only uint32_t)? It would also be desirable to create message queues statically.

**Comment by mohammad1603** [comment]
Thanks for the comment, the current implementation for queue of uint32_t, therefore the messageQSize changed to be "messageQCount" since it represents the count of the messages, this fix will be in the upcoming release.
as a future feature, a generic message queue can be added to PAL APIs.

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.

Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.

Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
