### ISSUE TITLE
pal_osThreadCreate() documents each thread to have a unique priority

### ISSUE THREAD

**Issue by rgrover** [ARMmbed/pal#32]
According to the documentation for `pal_osThreadCreate`, "_Each thread MUST be with unique priority_."

Why should created threads have unique priority? Why isn't it permissible to create a pool of threads (of equal priority) to divide available work?

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.

Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.

Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
