### ISSUE TITLE
issues with documentation of pal_osSemaphoreCreate()

### ISSUE THREAD

**Issue by rgrover** [ARMmbed/pal#39]
``` C++
/*! Create and initialize a Semaphore object
*
* @param[in] count: number of available resources
* @param[out] semaphoreID: holds the created semaphore ID handle - zero value indecates an error.
*
* \return PAL_SUCCESS when mutex created successfully.
*         Specific error in case of failure.
*/
palStatus_t pal_osSemaphoreCreate(uint32_t count, palSemaphoreID_t* semaphoreID);
```
- documentation for the out parameter `semaphoreID` says that an output value of 'zero' indicates an error. This seems to be redundant, since the palStatus_t returned by the API also indicates error. Does this mean that the platform implementor can use either of `*semaphoreID == 0` or an error return value to indicate failure. Perhaps what is meant is that 'when' there is an error,  `*semaphoreID == 0` upon return.
- At one point the documentation incorrectly refers to `mutex`. This could be a copy-paste error.

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.

Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.

Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
