### ISSUE TITLE
incomplete documentation for `pal_getAddressInfo`

### ISSUE THREAD

**Issue by rgrover** [ARMmbed/pal#43]
```C++
/*! this function will translate from a URL to a palSocketAddress_t which can be used with pal sockets. It supports both IP address as strings and URLs (using DNS lookup).
* @param[in] url the URL (or IP address sting) to be translated into a palSocketAddress_t.
* @param[out] address the address for the output of the translation.
*/
palStatus_t pal_getAddressInfo(const char* url, palSocketAddress_t* address, palSocketLength_t* addressLength);
```

In the above, documentation for parameter `addressLength` is missing.

**Comment by rgrover** [comment]
Is there any guidance to help the platform porter to choose the network interface to be used to translate the given URL?

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.

Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.

Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
