### ISSUE TITLE
confusing name for API pal_getAddressInfo()

### ISSUE THREAD

**Issue by rgrover** [ARMmbed/pal#45]
`pal_getAddressInfo` is actually an initializer for a `palSocketAddress_t`. The name `getAddressInfo` may confusingly suggest that it returns an address-info of some sort. Perhaps something like `pal_initSocketAddress()` would have been a better name.

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.

Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.

Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
