### ISSUE TITLE
test basicTCPclinetSendRecieve uses an integer literal for addressLength in call to pal_connect

### ISSUE THREAD

**Issue by rgrover** [ARMmbed/pal#46]
```C++
TEST(pal_socket, basicTCPclinetSendRecieve)
{
        ...

	result = pal_getAddressInfo(PAL_NET_TEST_SERVER_IP_STRING, &address, &addrlen);
	TEST_ASSERT_EQUAL(result, PAL_SUCCESS);

        ...

	result = pal_connect(sock, &address, 16);
	TEST_ASSERT_EQUAL(result, PAL_SUCCESS);

        ...
```

Notice that the third argument to pal_connect() [in the above] is `16`. It should be `PAL_IPV4_ADDRESS_SIZE`.

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.

Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.

Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
