### ISSUE TITLE
pal_recv() doesn't specify how long the asynchronous sockets should wait for inbound data

### ISSUE THREAD

**Issue by rgrover** [ARMmbed/pal#47]
`pal_recv()` might be enhanced by adding a timeout parameter for inbound data. Otherwise the documentation should clarify that the wait could potentially be boundless.

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.

Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.

Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
