### ISSUE TITLE
lack of documentation about how nonBlocking sockets behave for potentially blocking calls

### ISSUE THREAD

**Issue by rgrover** [ARMmbed/pal#49]
API documentation lacks clarity on the behaviour of non-blocking sockets. Calls like `pal_connect()`, `pal_send()`, and `pal_recv()` can block for either memory/buffer-space or inbound data. Do non-blocking sockets result in the invocation of callback-handlers? Should the user expect to setup a handler of type `palAsyncSocketCallback_t`? Why does `palAsyncSocketCallback_t` not have an event-type parameter to indicate the event?

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.

Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.

Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
