### ISSUE TITLE
why does pal_asynchronousSocket() take in a bool parameter for nonBlockingSocket?

### ISSUE THREAD

**Issue by rgrover** [ARMmbed/pal#50]
```C++
/*! get an asynchronous network socket
   ...
* @param[in] nonBlockingSocket if true the socket created is created as non-blocking (i.e. with O_NONBLOCK set)
   ...
*/
palStatus_t pal_asynchronousSocket(palSocketDomain_t domain, palSocketType_t type, bool nonBlockingSocket, uint32_t interfaceNum, palAsyncSocketCallback_t callback, palSocket_t* socket);
```

Doesn't the name `synchronousSocket` imply that nonBlocking behaviour is true?

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.

Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.

Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
