### ISSUE TITLE
why is `addressLen` passed in as a separate parameter to socket APIs taking `palSocketAddress_t`?

### ISSUE THREAD

**Issue by rgrover** [ARMmbed/pal#51]
Given an encoding of the address-family within `palSocketAddress_t`, why do we need APIs like pal_connect() to receive an `addressLen`? Why can't addressLen be deduced from `palSocketAddress_t`, or better still encoded within `palSocketAddress_t`?

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.

Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.

Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
