### ISSUE TITLE
minor typos in some names used in tests

### ISSUE THREAD

**Issue by rgrover** [ARMmbed/pal#52]
Refer to pal_socket_test.c. `basicTCPclinetSendRecieve` has a typo. `clinet` should have been `client`.

**Comment by rgrover** [comment]
There's also a typo in the following:

```
	memset(&interfaceInfo,0,sizeof(interfaceInfo));
	// check that re-addignt he network interface returns the same index
	pal_registerNetworkInterface(g_networkInterface, &interfaceIndex);
```

look at `check that re-addignt he`

**Comment by rgrover** [comment]
`Recieve` should be `Receive`.

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.

Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.

Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
