### ISSUE TITLE
pal_plat_imageReserveSpace does not check image size

### ISSUE THREAD

**Issue by bremoran** [ARMmbed/pal#54]
https://github.com/ARMmbed/pal/blob/541778965364c63b5a3e9f69823eafe74922bcf1/Source/Port/Reference-Impl/mbedOS/Update/pal_plat_update.cpp#L699

`pal_plat_imageReserveSpace` ignores both the imageID and imageSize variables. It should, at minimum, check that the image fits in the available space.

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.

Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.

Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
